# Generated by Django 3.2.6 on 2021-08-18 01:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(18)]),
        ),
    ]
